dependencies:
  - python = 3
  - pip:
    - beautifulsoup4
    - flask
    - ipykernel
    - matplotlib
    - numpy
    - keras
    - opencv-contrib-python
    - openpyxl
    - pandas
    - pyqt5
    - python-docx
    - scipy
    - scikit-learn
    - sympy
    - tensorflow
    - vtk
